name: redstone_cli
description: CLI tool for building Minecraft mods with Dart - The Flutter for Minecraft
version: 0.1.0

publish_to: none

environment:
  sdk: ^3.0.0

executables:
  redstone: redstone

dependencies:
  args: ^2.4.0
  mustache_template: ^2.0.0
  path: ^1.8.0
  yaml: ^3.1.0
  yaml_edit: ^2.1.0
  vm_service: ^14.0.0
  async: ^2.11.0
  io: ^1.0.0
  cli_util: ^0.4.0
  collection: ^1.18.0
  http: ^1.2.0
  crypto: ^3.0.3
  watcher: ^1.1.0
  redstone_test:
    path: ../redstone_test
  nocterm:
    git:
      url: https://github.com/Norbert515/nocterm.git
      ref: d1861c44b9521fa253727a865f8acd211ad61298

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0
