name: framework_tests
description: A Minecraft mod built with Redstone
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  ffi: ^2.1.0
  dart_mc:
    path: /Users/norbertkozsir/IdeaProjects/vide_mc/packages/dart_mc

dev_dependencies:
  redstone_test:
    path: /Users/norbertkozsir/IdeaProjects/vide_mc/packages/redstone_test

# Redstone configuration
redstone:
  minecraft_version: "1.21.11"
  org: com.redstone
  author: Redstone Team
