name: redstone_test
description: Testing library for Minecraft mods built with dart_mod_server, built on top of package:test
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  test: ^1.24.0
  matcher: ^0.12.0
  dart_mod_server:
    path: ../dart_mod_server

dev_dependencies:
  lints: ^5.0.0
