name: minecraft_flutter_dev_client
description: Client-side Flutter UI for Minecraft Flutter Dev
version: 1.0.0
publish_to: none

resolution: workspace

environment:
  sdk: ^3.5.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dart_mod_client:
    path: ../../../packages/dart_mod_client
  dart_mod_common:
    path: ../../../packages/dart_mod_common
  minecraft_ui:
    path: ../../../packages/minecraft_ui
  minecraft_flutter_dev_common:
    path: ../common
