name: minecraft_flutter_dev_server
description: Server-side logic for Minecraft Flutter Dev
version: 1.0.0
publish_to: none

resolution: workspace

environment:
  sdk: ^3.5.0

dependencies:
  ffi: ^2.1.0
  dart_mod_server:
    path: ../../../packages/dart_mod_server
  dart_mod_common:
    path: ../../../packages/dart_mod_common
  minecraft_flutter_dev_common:
    path: ../common
  minecraft_mcp:
    path: ../../../packages/minecraft_mcp

dev_dependencies:
  redstone_test:
    path: ../../../packages/redstone_test
