name: nocterm_minecraft
description: Minecraft block-based rendering backend for nocterm
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  nocterm:
    git:
      url: https://github.com/Norbert515/nocterm.git
      ref: d1861c44b9521fa253727a865f8acd211ad61298
  dart_mod_server:
    path: ../dart_mod_server
  dart_mod_common:
    path: ../dart_mod_common
