name: example_mod_common
description: Shared types for Example Mod (client/server agnostic)
version: 1.0.0
publish_to: none

resolution: workspace

environment:
  sdk: ^3.5.0

dependencies:
  dart_mod_common:
    path: ../../../../packages/dart_mod_common
